@echo off
setlocal enabledelayedexpansion
:: Always run in this script's own folder (the repo root). The old hardcoded
:: "cd /d C:\arona" pointed at a path that does not exist on this machine, so the
:: cd failed silently and every git command below ran in whatever directory the
:: script happened to be launched from -> "fatal: not a git repository", and
:: "git add ." would have staged an unrelated folder.
:: Use pushd, not "cd /d": this repo lives on a UNC path (\\server\share\arona) and
:: cmd refuses a UNC path as a current directory ("CMD does not support UNC paths as
:: current directories"). pushd transparently maps it to a temporary drive letter, so
:: git and python resolve correctly; on a local path it behaves exactly like cd.
pushd "%~dp0"

echo [%date% %time%] Checking for Git repository changes...

:: Check for changes (no ">nul" redirect — a shadow file named "nul" in the repo
:: would otherwise swallow this output and git can never index such a file)
set CHANGES=
for /f %%i in ('git status --porcelain') do if not defined CHANGES set CHANGES=yes
if not defined CHANGES (
    echo [%date% %time%] No changes detected. Nothing to commit.
    echo Waiting 30 seconds before exiting...
    timeout /t 30
    exit /b
)

echo [%date% %time%] Changes detected. Staging files...
git add .

echo [%date% %time%] Generating AI commit message using Gemini...
python generate_msg.py

echo [%date% %time%] Checking for co-authors (Live Share session)...
if exist coauthors.txt (
    echo. >> .commit_msg.txt
    for /f "usebackq delims=" %%A in ("coauthors.txt") do (
        if not "%%A"=="" echo Co-authored-by: %%A >> .commit_msg.txt
    )
    echo [%date% %time%] Co-authors added from coauthors.txt
) else (
    echo [%date% %time%] No coauthors.txt found, skipping.
)

echo --------------------------------------------------
echo [Commit Message Generated by AI]:
type .commit_msg.txt
echo --------------------------------------------------

echo [%date% %time%] Committing changes...
git commit -F .commit_msg.txt

if exist .commit_msg.txt del .commit_msg.txt

echo [%date% %time%] Pushing changes to origin main (force)...
git push origin main --force

if %errorlevel% equ 0 (
    echo [%date% %time%] Auto-sync completed successfully!
) else (
    echo [%date% %time%] An error occurred during push!
)

echo Waiting 30 seconds before exiting...
timeout /t 30