@echo off
setlocal enabledelayedexpansion
cd /d "C:\arona"

echo [%date% %time%] Checking for Git repository changes...

:: Check for changes
git status --porcelain | findstr /r "^" >nul
if %errorlevel% neq 0 (
    echo [%date% %time%] No changes detected. Nothing to commit.
    echo Waiting 30 seconds before exiting...
    timeout /t 30
    exit /b
)

echo [%date% %time%] Changes detected. Staging files...
git add .

echo [%date% %time%] Generating AI commit message using Gemini...
python generate_msg.py

echo --------------------------------------------------
echo [Commit Message Generated by AI]:
type .commit_msg.txt
echo --------------------------------------------------

echo [%date% %time%] Committing changes...
git commit -F .commit_msg.txt

if exist .commit_msg.txt del .commit_msg.txt

echo [%date% %time%] Pushing changes to origin main (force)...
git push origin main --force

if %errorlevel% equ 0 (
    echo [%date% %time%] Auto-sync completed successfully!
) else (
    echo [%date% %time%] An error occurred during push!
)

echo Waiting 30 seconds before exiting...
timeout /t 30